En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [9]:
import numpy as np
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[1, 2, 3], [3, 4, 5]])
    
def somme(A,B):
    print(A)
    print("+")
    print(B)
    print("=")
    C=np.add(A,B)
    print(C)

somme(A,B)
    

[[1 2 3]
 [3 4 5]]
+
[[1 2 3]
 [3 4 5]]
=
[[ 2  4  6]
 [ 6  8 10]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [80]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[1, 2],[3,4],[5, 6]])

C = np.array([[1, 2, 3], [3, 4, 5]])

def produit(A,B):
    da = np.shape(A)
    db = np.shape(B)
    if(da[1]==db[0]):
        print(A)
        print("*")
        print(B)
        print("=")
        C=np.matmul(A,B)
        print(C)
    else:
        print("impossible")
                
            
    
produit(A,B)
produit(A,C)

[[1 2 3]
 [3 4 5]]
*
[[1 2]
 [3 4]
 [5 6]]
=
[[22 28]
 [40 52]]
impossible


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [89]:
m = [[0.2,0.6,0.2],[0.1,0.6,0.3],[0.2,0.7,0.1]]
n = [[0.5,0.5,0.5],[0.4,0.4,0.4],[0.1,0.1,0.1]]
bi = [[0.5,0.4,0.1],[0.4,0.5,0.5],[0.1,0.1,0.4]]
def eststochastique(P):
    d = np.shape(P)
    for j in range (d[1]):
        somme=0
        for i in range(d[0]):
            somme+=P[i][j]
        if(somme!=1):
            print("Matrice Non stochastique")
            return;
    print("Matrice stochastique")
    return;

eststochastique(m)
eststochastique(n)

def estbistochastique(P):
    d = np.shape(P)
    for j in range (d[1]):
        somme=0
        for i in range(d[0]):
            somme+=P[i][j]
        if(somme!=1):
            print("Matrice Non bistochastique")
            return;
    for j in range (d[0]):
        somme=0
        for i in range(d[1]):
            somme+=P[i][j]
        if(somme!=1):
            print("Matrice Non bistochastique")
            return;
    print("Matrice bistochastique")
    return;
    
estbistochastique(bi)
estbistochastique(m)

G = np.array([[0.95, 0.05], [0.03, 0.97]])
h = np.array([[0.375, 0.625]])
def vecteurstable(G, h):
    a = np.shape(h)
    print(h.dot(G))
    for i in range (a[0]):
        if (h*G == h):
            print(h +" n'est pas un vecteur stable de "+ G)
            return
    print(h +" est un vecteur stable de "+ G)
    
vecteurstable(G, h)

Matrice Non stochastique
Matrice stochastique
Matrice bistochastique
Matrice Non bistochastique
[[0.375 0.625]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [94]:
A = np.array([[1, 2, 3], [3, 4, 5]])
def trans(A):
    d = np.shape(A)
    B= np.ndarray(shape=(d[1],d[0]), dtype=int)
    for i in range (d[0]):
        for j in range (d[1]):
            B[j,i]=A[i,j]
    return B;

print(trans(A))
    

[[1 3]
 [2 4]
 [3 5]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)